# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34bef69ead3d13bca39034ca65b4bd7f2e919b22725f3ec180a061e4dea35f82123f61e32d7a9e48ec0d95ed68307604d17f4d0444f2e622eee3e5e82ced277d

test:
  secret_key_base: 7e047341994c0857b8d93c4e1a5d26c80f763f0fc0d7f5dcbe972f175778496fd3c884f260d19c9be9a85139474277861c09b716e5c75e715743b538df284839

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
